///////////////////////////////////////////////////////////
//  IHeuristicSearchProblem.cs
//  Implementation of the Interface IHeuristicSearchProblem
//  Generated by Enterprise Architect
//  Created on:      29-Jul-2006 18:36:23
//  Original author: Oliver Kuehne
///////////////////////////////////////////////////////////
using OKSearchRoom;

namespace OKHeuristicSearchRoom
{
    /// <summary>
    /// Definiert Funktionen, die für ein allgemeines SuchProblem mit Heuristik notwendig sind
    /// </summary>
	public interface IHeuristicSearchProblem : ISearchProblem 
	{
        /// <summary>
        /// Liefert oder setzt die Werte-Heuristik, die verwendet wird.
        /// </summary>
        IHeuristicValue HeuristicValue
        {
            get;
            set;
        }
	}//end IHeuristicSearchProblem

}//end namespace OKSearchRoom