///////////////////////////////////////////////////////////
//  IProblem.cs
//  Implementation of the Interface IProblem
//  Generated by Enterprise Architect
//  Created on:      29-Jul-2006 18:36:23
//  Original author: Oliver Kuehne
///////////////////////////////////////////////////////////




using OKSearchRoom;
namespace OKSearchRoom {
    /// <summary>
    /// Definiert Funktionen, die für ein allgemeines Problem notwendig sind
    /// </summary>
	public interface IProblem 
	{

		/// <summary>
		/// Vergleicht den übergebenen Knoten mit dem Zielknoten oder einem Zielkriterium.
		/// </summary>
		/// <returns>Gibt true zurück, wenn der Knoten einen Zielknoten darstellt, oder das
		/// Zielkriterium erfüllt.</returns>
		/// <param name="node">Der Knoten, den es zu untersuchen gilt.</param>
		bool CompareNodes(INode node);

		/// <summary>
		/// Beschreibt die Knoten, bei dem die Suche startet.
		/// </summary>
        INode[] FirstNodes{get;} 

		/// <summary>
		/// Wird aufgerufen, wenn der gesamte Suchraum durchsucht wurde, ohne einen
		/// Zielknoten zu finden.
		/// </summary>
		void OnFoundNoneDestination();

        /// <summary>
        /// Wird aufgerufen, wenn der Zielknoten oder das Zielkriterium gefunden wurde.
        /// </summary>
        /// <param name="destination">Der gefunden Knoten.</param>
        /// <param name="searchMethod">Gibt die Suchmethode an, mit der die Lösung gefunden wurde.</param>
        bool OnFoundDestination(INode destination, ISearchMethod searchMethod);

        /// <summary>
        /// Wird aufgerufen, wenn die Suche beginnt.
        /// </summary>
        void OnStartSearch();
	}//end IProblem

}//end namespace OKSearchRoom