///////////////////////////////////////////////////////////
//  ISearchEventHandler.cs
//  Implementation of the Interface ISearchEventHandler
//  Generated by Enterprise Architect
//  Created on:      29-Jul-2006 18:36:24
//  Original author: Oliver Kuehne
///////////////////////////////////////////////////////////




namespace OKSearchRoom {
	/// <summary>
	/// Beschreibt ein Interface, um Informationen während des Suchens nach Außen zu
	/// geben.
	/// </summary>
	public interface ISearchEventHandler 
	{

		/// <summary>
		/// Diese Funktion wird von der jeweiligen Suchmethode nach jeder Knotengenerierung
		/// aufgerufen.
		/// </summary>
		/// <param name="countInspectedNodes">Gibt die Anzahl der bereits geprüften Knoten
		/// an.</param>
		/// <param name="countCurrentNodes">Gibt die Anzahl der Knoten in der Knotenmenge
		/// an.</param>
		/// <param name="cancel">Wird über Cancel false zurückgegben endet die Suchmethode.
		/// Sie kann dann über Continue fortgesetzt werden.</param>
		void SearchEvent(int countInspectedNodes, int countCurrentNodes, ref bool cancel);
	}//end ISearchEventHandler

}//end namespace OKSearchRoom