///////////////////////////////////////////////////////////
//  ISearchMethod.cs
//  Implementation of the Interface ISearchMethod
//  Generated by Enterprise Architect
//  Created on:      29-Jul-2006 18:36:24
//  Original author: Oliver Kuehne
///////////////////////////////////////////////////////////



using System.Collections.Generic;
using OKSearchRoom;
namespace OKSearchRoom {
	/// <summary>
	/// Definiert allgemeine Methoden, die für ein Suchverfahren genutzt werden.
	/// </summary>
	public interface ISearchMethod 
	{

		/// <summary>
		/// Ein unterbrochene Suche wird fortgesetzt.
		/// </summary>
		void Continue();

		/// <summary>
		/// Ein Suchverfahren kann mit einem Eventhandler versorgt werden. Mit Hilfe dieses
		/// Eventhandlers ist es möglich, dass von Außen Informationen während der Suche
		/// empfangen werden. Ebenso ist mittels der Eventhandler ein Stoppen des
		/// Suchverfahrens möglich.
		/// </summary>
		ISearchEventHandler EventHandler{
			get;
			set;
		}

		/// <summary>
		/// Die Suche wird gestartet.
		/// </summary>
		void Run();

        /// <summary>
        /// Gibt die Knotenmenge zurück, oder setzt diese.
        /// </summary>
        IEnumerable<INode> NodeSet
        {
            get;
            set;
        }

        /// <summary>
        /// Gibt die Anzahl der bisher untersuchten Knoten zurück.
        /// </summary>
        int InspectedNodes
        {
            get;
        }
	}//end ISearchMethod

}//end namespace OKSearchRoom