///////////////////////////////////////////////////////////
//  ISearchProblem.cs
//  Implementation of the Interface ISearchProblem
//  Generated by Enterprise Architect
//  Created on:      29-Jul-2006 18:36:24
//  Original author: Oliver Kuehne
///////////////////////////////////////////////////////////




using OKSearchRoom;
namespace OKSearchRoom {
    /// <summary>
    /// Definiert Funktionen, die für ein allgemeines SuchProblem notwendig sind
    /// </summary>
	public interface ISearchProblem : IProblem 
	{

		/// <summary>
		/// Für den übergebenen Knoten werden neue Unterknoten generiert.
		/// </summary>
		/// <returns>Gibt die Menge der generierten Knoten als Array zurück.</returns>
		/// <param name="node">Anhand des übergebenen Knotens werden neue Unterknoten
		/// generiert.</param>
		/// <param name="maxCount">Beschränkt die Anzahl der Unterknoten.</param>
		INode[] GenerateChildren(INode node, int maxCount);
	}//end ISearchProblem

}//end namespace OKSearchRoom